export type TripItem = {
  reporting_point: {
    name: string;
  };
  reporting_time: {
    hour: string;
    minute: string;
    ampm: string;
  };
  final_driver_advance_to_company_account: boolean;
  isUnfullfilled: boolean;
  default_start_today: boolean;
  tripsheet_id: string | null;
  payment: string | null;
  advance_payments: any[];
  ent_od_client_email: any[];
  ent_od_driver_status: string;
  is_ent_od: boolean;
  trip_ratio: number;
  generic_tripsheet_id: string | null;
  trip_mode: string;
  trip_type: string;
  estimated_distance: number;
  extra_driver_payment: number;
  extra_client_payment: number;
  estimated_time: number;
  extra_payment_required: boolean;
  drop_count: number;
  prolonged_booking: boolean;
  is_active: boolean;
  payment_restriction: string;
  final_driver_advance_to_driver_account: boolean;
  custom_account: string | null;
  paid_to: string;
  status: string;
  cancelled_at: number;
  _id: string;
  handling_charges: number;
  listing_id: string;
  area_id: string;
  client_name: string;
  city_code: string;
  pick_up_at: number;
  client_id: string;
  hub_id: string;
  vehicle_id: string;
  vehicle_type: string;
  fo_id: string;
  pricing_id: string;
  created_at: number;
  backup_driver_array: any[];
  geofence_events: any[];
  location: any[];
  __v: number;
  createdAt: string;
  updated_at: string;
  booking_management_reference: string;
  final_driver_owner_contact: number;
  final_driver_owner_name: string;
  final_driver_rate: number;
  provitional_cost: number;
  final_driver_remarks: string;
  final_driver_arranged_by_id: string;
  final_driver_arranged_by: string;
  final_driver_type: string;
  final_driver_vehicle_no: string;
  final_driver_contact: number | null;
  final_driver_name: string;
  final_driver_advance: number;
  estimated_price: number;
  optimal_cost: number;
  locations: any[];
};

export type HubItem = {
  location: {
    coordinates: any;
  };
  active: boolean;
  tardiness_cap: number;
  status: string;
  created_from: string;
  _id: string;
  name: string;
  area_id: string;
  client_id: string;
  fo_id: string;
  area_lead_id: string;
  info: {
    position: {
      latitude: number;
      longitude: number;
    };
    place_name: string;
    vicinity: string;
    formatted_address: string;
    address: string;
    pincode: string;
    google_id: string;
    place_type: string;
  };
  city_code: string;
  created_at: string;
  updated_at: string;
  __v: number;
};
